spring:
  datasource:
    url: jdbc:mysql://localhost:3306/htnb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "MySuperSecretKeyMySuperSecretKeyMySuperSecretKey"
  expiration: 3600000
  refresh:
    expiration: 604800000

